extends:
  - react-app
  - react-app/jest
rules:
  no-console:
    - warn
    - allow:
        - error
  # converts any string concatenation into a template literal
  prefer-template: error
# disables annoying rule on Storybook stories
overrides:
  - files:
      - "**/*.stories.*"
    rules:
      import/no-anonymous-default-export: "off"
